"use client";

import { FileCheck2, FlaskConical, LockKeyhole } from "lucide-react";
import { useActionState } from "react";
import { startApplicationExtraction } from "@/app/(protected)/applications/[applicationId]/extraction-actions";
import { Alert } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";

export function ReviewReadyPanel({applicationId="00000000-0000-4000-8000-000000000000",extractionMode="live"}:{applicationId?:string;extractionMode?:"live"|"demo"}){const[state,action,pending]=useActionState(startApplicationExtraction.bind(null,applicationId),{status:"idle" as const});return <Card className="border-[#bfddd2] bg-[var(--success-soft)]"><CardContent className="pt-6"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-4"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-[var(--surface)] text-[var(--primary)]"><FileCheck2 className="size-5" aria-hidden="true"/></span><div><span className="text-xs font-bold uppercase tracking-[.12em] text-[var(--primary)]">Next task · Review</span><h2 className="mt-2 text-xl font-bold">Documents are ready for extraction</h2><p className="mt-2 max-w-lg text-sm leading-6 text-[var(--muted)]">Create candidate fields from all three private documents, then check every value before verification.</p>{extractionMode==="demo"&&<p role="status" className="mt-4 flex w-fit items-center gap-2 rounded-full border border-[#d6b870] bg-[#fff7df] px-3 py-2 text-xs font-bold text-[#70520b]"><FlaskConical className="size-4" aria-hidden="true"/>Demo extraction—not processed by live AI</p>}</div></div><form action={action}><Button type="submit" loading={pending}>{pending?"Extracting three documents…":extractionMode==="demo"?"Use Demo extraction":"Extract with Gemini"}</Button></form></div>{state.status==="error"&&<Alert tone="error" title="Extraction needs attention" className="mt-5"><p>{state.message}</p></Alert>}<p className="mt-5 flex gap-2 border-t border-[#bfddd2] pt-4 text-xs text-[var(--muted)]"><LockKeyhole className="mt-0.5 size-4 shrink-0" aria-hidden="true"/>Verification stays locked until you review every extracted field.</p></CardContent></Card>}
