"use client";

import { useActionState } from "react";
import { AlertCircle, CheckCircle2, CircleAlert, FileSearch, Send } from "lucide-react";
import { Alert } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { StatusBadge } from "@/components/status-badge";
import { runApplicationVerification, sendApplicationToBuyer, type VerificationActionState } from "@/app/(protected)/applications/[applicationId]/verification-actions";
import type { VerificationCheck, VerificationStatus } from "@/lib/verification/rules-v1";

const initialState: VerificationActionState = { status: "idle" };
const icons = { pass: CheckCircle2, review: CircleAlert, fail: AlertCircle };

export function VerificationPanel({ applicationId, status, overallResult, checks, completedAt, sourceDocuments }: { applicationId: string; status: string; overallResult: VerificationStatus | null; checks: VerificationCheck[]; completedAt: string | null; sourceDocuments: Array<{id:string;label:string}> }) {
  const [runState, runAction, running] = useActionState(runApplicationVerification.bind(null, applicationId), initialState);
  const [sendState, sendAction, sending] = useActionState(sendApplicationToBuyer.bind(null, applicationId), initialState);
  const hasRun = checks.length === 12 && overallResult !== null;
  const canSend = status === "checks_complete" && overallResult !== "fail";
  const pendingBuyer = status === "buyer_pending";

  if (!hasRun) return <Card><CardContent className="pt-6"><div className="grid size-11 place-items-center rounded-xl bg-[var(--success-soft)] text-[var(--primary)]"><FileSearch className="size-5" aria-hidden="true" /></div><h2 className="mt-5 text-2xl font-bold tracking-[-.03em]">Run evidence checks</h2><p className="mt-2 max-w-xl text-sm leading-6 text-[var(--muted)]">ProofFlow will compare the reviewed names, references, dates, currencies, totals, delivery acknowledgement, and duplicates. These checks describe evidence consistency—not creditworthiness or finance approval.</p>{runState.status === "error" && <Alert tone="error" title="Verification not completed" className="mt-5"><p>{runState.message}</p></Alert>}<form action={runAction} className="mt-6"><Button type="submit" loading={running}>{running ? "Running 12 checks…" : "Run verification checks"}</Button></form></CardContent></Card>;

  return <section aria-labelledby="verification-report-heading" className="space-y-5"><Card><CardContent className="pt-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><span className="text-xs font-bold uppercase tracking-[.12em] text-[var(--primary)]">Evidence consistency · v1</span><h2 id="verification-report-heading" className="mt-2 text-2xl font-bold tracking-[-.03em]">Verification report</h2><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{completedAt ? `Completed ${new Intl.DateTimeFormat("en-ZA", { dateStyle: "medium", timeStyle: "short" }).format(new Date(completedAt))}. ` : ""}Every result below shows the facts compared and where they came from.</p></div><StatusBadge status={overallResult === "pass" ? "success" : overallResult === "review" ? "review" : "error"}>{overallResult === "pass" ? "Checks clear" : overallResult === "review" ? "Needs review" : "Checks failed"}</StatusBadge></div>{overallResult === "fail" && <Alert tone="error" title="Buyer request blocked" className="mt-5"><p>Correct the failed evidence and run a new verification before sending this application.</p></Alert>}{overallResult === "review" && <Alert tone="info" title="Human attention recorded" className="mt-5"><p>There are no blocking contradictions. The buyer will see these review items when confirming the transaction.</p></Alert>}</CardContent></Card>
    <div className="grid gap-3 xl:grid-cols-2">{checks.map((check) => { const Icon = icons[check.status]; const sources=sourceDocuments.filter(document=>check.sourceDocumentIds.includes(document.id)); return <Card key={check.ruleId}><CardContent className="pt-5"><div className="flex items-start gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-full bg-[var(--soft)]"><Icon className="size-4" aria-hidden="true" /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-bold">{check.ruleId} · {check.title}</h3><StatusBadge status={check.status === "pass" ? "success" : check.status === "review" ? "review" : "error"}>{check.status}</StatusBadge></div><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{check.explanation}</p><dl className="mt-4 grid gap-2 rounded-xl bg-[var(--soft)] p-3 sm:grid-cols-2">{Object.entries(check.comparedValues).map(([label, value]) => <div key={label}><dt className="text-[11px] font-bold uppercase tracking-[.08em] text-[var(--muted)]">{label}</dt><dd className="mt-1 break-words text-sm font-semibold">{value ?? "Missing"}</dd></div>)}</dl><div className="mt-3 flex flex-wrap gap-x-3 gap-y-1 text-xs">{sources.length?sources.map(source=><a key={source.id} href={`#document-${source.id}`} className="min-h-7 font-semibold text-[var(--primary)] underline-offset-4 hover:underline">View {source.label}</a>):<span className="text-[var(--muted)]">Buyer confirmation record</span>}</div></div></div></CardContent></Card>; })}</div>
    {(runState.status === "error" || sendState.status === "error") && <Alert tone="error" title="Action not completed"><p>{runState.status === "error" ? runState.message : sendState.message}</p></Alert>}
    <Card><CardContent className="pt-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="font-bold">{pendingBuyer ? "Buyer confirmation requested" : canSend ? "Ready for buyer confirmation" : "Verification requires correction"}</h3><p className="mt-1 text-sm text-[var(--muted)]">{pendingBuyer ? "The request is now in the buyer organization's secure queue." : canSend ? "The buyer will receive the reviewed transaction and every non-blocking warning." : "Failed checks remain visible and prevent an unsafe handoff."}</p></div>{pendingBuyer ? <StatusBadge status="review">Waiting for buyer</StatusBadge> : <form action={sendAction}><Button type="submit" loading={sending} disabled={!canSend}><Send className="size-4" aria-hidden="true" />{sending ? "Sending…" : "Send to buyer"}</Button></form>}</div>{status === "checks_complete" && <form action={runAction} className="mt-4"><button type="submit" disabled={running} className="min-h-11 text-sm font-semibold text-[var(--primary)] underline-offset-4 hover:underline disabled:opacity-50">{running ? "Rerunning checks…" : "Run a fresh verification"}</button></form>}</CardContent></Card>
  </section>;
}
