import { EmptyState } from "@/components/empty-state";
import { PageHeading } from "@/components/page-heading";
import { StatusBadge } from "@/components/status-badge";
import { Card,CardContent } from "@/components/ui/card";
import type { DashboardData } from "@/lib/dashboard/repository";
import { Metrics,QueueButton } from "./shared";

export function FunderDashboard({data}:{data:Extract<DashboardData,{role:"funder"}>}){
  const count=data.applications.length;
  return <div className="page-enter mx-auto max-w-6xl"><PageHeading eyebrow="Funder overview" title="Evidence ready for review." description="Every package below includes deterministic checks and a buyer confirmation. Funding decisions remain yours."/><Metrics items={data.metrics}/><Card className="mt-8"><CardContent className="pt-6"><div className="flex items-center justify-between"><div><h2 className="text-xl font-bold">Buyer-confirmed applications</h2><p className="mt-1 text-sm text-[var(--muted)]">No unconfirmed or disputed packages appear here.</p></div><StatusBadge status="success">{count} ready</StatusBadge></div>{count?<div className="mt-6 divide-y divide-[var(--border)]">{data.applications.map(application=><article key={application.id} className="grid gap-4 py-5 lg:grid-cols-[1fr_auto] lg:items-center"><div><div className="flex flex-wrap items-center gap-2"><b>{application.supplier}</b><StatusBadge status="success">Buyer Confirmed ✓</StatusBadge><StatusBadge status={application.warnings?"review":"success"}>{application.warnings?`${application.warnings} ${application.warnings===1?"review item":"review items"}`:"Checks clear"}</StatusBadge></div><p className="mt-2 text-sm text-[var(--muted)]">{application.buyer} · {application.amount} · Due {application.dueDate} · Confirmed {application.confirmed}</p></div><div className="flex flex-wrap gap-2"><QueueButton label="Review evidence" href={application.href}/><QueueButton label={application.certificateHref?"Certificate":"Unavailable"} href={application.certificateHref??undefined}/></div></article>)}</div>:<EmptyState title="No applications ready" description="Only buyer-confirmed evidence packages will appear here."/>}</CardContent></Card><p className="mt-4 text-xs text-[var(--muted)]">All offer and funding actions in ProofFlow are hackathon simulations.</p></div>;
}
