import { Clock3, FileText } from "lucide-react";
import { PageHeading } from "@/components/page-heading";
import { StatusBadge } from "@/components/status-badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import type { DashboardData } from "@/lib/demo/repository";
import { Metrics, QueueButton } from "./shared";
export function SmeDashboard({data}:{data:Extract<DashboardData,{role:"sme"}>}){return <div className="page-enter mx-auto max-w-6xl"><PageHeading eyebrow="SME overview" title="Good morning, Amara." description="Your next step is always shown first. Build the evidence once, then follow it through confirmation and review." action={<Button disabled title="Application builder arrives in Phase 3">Start application</Button>} /><Metrics items={data.metrics}/><section className="mt-8 grid gap-6 lg:grid-cols-[1.3fr_.7fr]"><Card><CardContent className="pt-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><span className="text-xs font-bold uppercase tracking-[.1em] text-[var(--primary)]">Current application</span><h2 className="mt-2 text-2xl font-bold tracking-tight">{data.application.buyer}</h2></div><StatusBadge status="success">{data.application.status}</StatusBadge></div><div className="mt-7 grid grid-cols-2 gap-3 rounded-xl bg-[var(--soft)] p-4 text-sm"><span><small className="block text-[var(--muted)]">Reference</small><b>{data.application.id}</b></span><span><small className="block text-[var(--muted)]">Invoice value</small><b>{data.application.amount}</b></span></div><Progress className="mt-7" label="Evidence journey" value={data.application.progress}/><div className="mt-6 flex items-center justify-between gap-4"><p className="flex items-center gap-2 text-sm text-[var(--muted)]"><Clock3 className="size-4" />{data.application.next}</p><QueueButton label="View application"/></div></CardContent></Card><Card className="bg-[var(--primary-pressed)] text-white"><CardContent className="pt-6"><FileText className="size-6 text-[#9fd4c5]"/><h2 className="mt-10 text-2xl font-semibold tracking-tight">Your proof is reusable.</h2><p className="mt-3 text-sm leading-6 text-[#c7d9d3]">Every buyer-confirmed application adds explainable evidence to your Trust Passport—not an opaque credit score.</p></CardContent></Card></section></div>}
