import { createClient } from "@supabase/supabase-js";
const url=process.env.PROOFFLOW_TEST_SUPABASE_URL,key=process.env.PROOFFLOW_TEST_PUBLISHABLE_KEY,password=process.env.PROOFFLOW_DEMO_PASSWORD;if(!url||!key||!password)throw new Error("Hosted Demo Coupa test configuration is missing.");
const client=()=>createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});const buyer=client(),sme=client(),funder=client();
const signIn=async(current,email)=>{const {error}=await current.auth.signInWithPassword({email,password});if(error)throw error;};
await Promise.all([signIn(buyer,"buyer.demo@proofflow.example"),signIn(sme,"sme.demo@proofflow.example"),signIn(funder,"funder.demo@proofflow.example")]);
const {data:connections,error:connectionError}=await buyer.from("integration_connections").select("id,provider,mode,status,demo_scenario");if(connectionError||connections.length!==1||connections[0].mode!=="demo")throw new Error("Buyer could not read its safe Demo Coupa connection metadata.");
const secretRead=await buyer.from("integration_connections").select("credential_reference");if(!secretRead.error)throw new Error("Buyer browser could read credential_reference.");
for(const [label,current] of [["SME",sme],["funder",funder]]){const {data,error}=await current.from("integration_connections").select("id");if(error||data.length)throw new Error(`${label} could read a buyer connection.`);}
const directUpdate=await buyer.from("integration_connections").update({demo_scenario:"already_paid"}).eq("id",connections[0].id).select("id");if(!directUpdate.error&&directUpdate.data.length)throw new Error("Buyer bypassed the scenario RPC with a direct table update.");
const scenario=await buyer.rpc("set_demo_coupa_scenario",{target_connection_id:connections[0].id,target_scenario:"match"});if(scenario.error)throw scenario.error;
const wrongRole=await funder.rpc("set_demo_coupa_scenario",{target_connection_id:connections[0].id,target_scenario:"match"});if(!wrongRole.error)throw new Error("Funder changed a buyer connection.");
const verifiedApplicationId="650edca7-d591-4c82-adfc-915be0d0d2a1";
const {data:verificationRun,error:verificationError}=await sme.from("verification_runs").select("id").eq("application_id",verifiedApplicationId).eq("status","completed").order("completed_at",{ascending:false}).limit(1).single();if(verificationError)throw verificationError;
const replay=await sme.rpc("persist_demo_coupa_result_v1",{target_application_id:verifiedApplicationId,target_connection_id:connections[0].id,target_idempotency_key:`${verificationRun.id}:match`,target_correlation_id:"coupa-replay-test",target_outcome:"system_verified",target_evidence:{},target_checks:[],target_error_code:null});if(replay.error||!replay.data.replayed)throw new Error("Demo Coupa sync replay was not idempotent.");
for(const [label,current] of [["SME",sme],["buyer",buyer],["funder",funder]]){const {data,error}=await current.from("external_evidence_snapshots").select("id,payload_hash").eq("application_id",verifiedApplicationId);if(error||data.length!==1||data[0].payload_hash.length!==64)throw new Error(`${label} could not read the eligible evidence snapshot.`);}
const snapshotUpdate=await sme.from("external_evidence_snapshots").update({payload_hash:"b".repeat(64)}).eq("application_id",verifiedApplicationId).select("id");if(!snapshotUpdate.error&&snapshotUpdate.data.length)throw new Error("SME modified an immutable evidence snapshot.");
const {data:ineligible,error:ineligibleError}=await funder.from("applications").select("id").eq("status","draft");if(ineligibleError||ineligible.length)throw new Error("Funder could see an ineligible draft.");
console.log("PASS: Demo Coupa connection metadata, credential protection, tenant RLS, eligible snapshot visibility, immutability, prerequisite filtering, and idempotent replay are enforced.");
