import type { Metadata } from "next";
import { ArrowRight, Building2, FileCheck2, HandCoins } from "lucide-react";
import { enterDemoWorkspace } from "@/app/(auth)/login/actions";
import { Logo } from "@/components/logo";
import { LoginForm } from "@/features/auth/login-form";
import type { Role } from "@/types/domain";
export const metadata:Metadata={title:"Sign in"};
const demos:Array<{role:Role;label:string;detail:string;icon:typeof Building2}>=[{role:"sme",label:"SME workspace",detail:"Create and track evidence",icon:Building2},{role:"buyer",label:"Buyer workspace",detail:"Confirm delivery requests",icon:FileCheck2},{role:"funder",label:"Funder workspace",detail:"Review simulated offers",icon:HandCoins}];
export default function LoginPage(){return <main className="login-layout"><section className="login-story"><Logo className="text-white" /><div className="max-w-xl"><span className="text-xs font-bold uppercase tracking-[.14em] text-[#9fd4c5]">From invoice to cash readiness</span><h1 className="mt-5 text-5xl font-semibold leading-[.98] tracking-[-.06em] text-white sm:text-6xl">One trusted story for every side of the invoice.</h1><p className="mt-6 max-w-lg text-base leading-7 text-[#c7d9d3]">SMEs provide the evidence, buyers confirm the work, and funders review one explainable package.</p></div><p className="text-xs text-[#9fd4c5]">Hackathon demonstration · Synthetic data · No real money moves</p></section><section className="login-panel"><div className="w-full max-w-md"><span className="text-xs font-bold uppercase tracking-[.12em] text-[var(--primary)]">Welcome back</span><h2 className="mt-3 text-3xl font-semibold tracking-[-.045em]">Sign in to ProofFlow</h2><p className="mt-3 text-sm leading-6 text-[var(--muted)]">Use your account when Supabase is connected, or enter a fictional demo workspace now.</p><div className="mt-8"><LoginForm /></div><div className="my-7 flex items-center gap-3 text-xs text-[var(--muted)]"><span className="h-px flex-1 bg-[var(--border)]" />Hackathon demo roles<span className="h-px flex-1 bg-[var(--border)]" /></div><div className="space-y-2">{demos.map(({role,label,detail,icon:Icon})=><form action={enterDemoWorkspace} key={role}><input type="hidden" name="role" value={role} /><button className="group flex min-h-16 w-full items-center gap-3 rounded-xl border border-[var(--border)] bg-[var(--surface)] px-3 text-left transition-colors hover:bg-[var(--soft)] focus-visible:outline-none focus-visible:ring-3 focus-visible:ring-[var(--focus)]"><span className="grid size-10 place-items-center rounded-lg bg-[var(--soft)] text-[var(--primary)]"><Icon aria-hidden="true" className="size-4" /></span><span className="flex-1"><b className="block text-sm">{label}</b><small className="text-[var(--muted)]">{detail}</small></span><ArrowRight aria-hidden="true" className="size-4 text-[var(--muted)]" /></button></form>)}</div></div></section></main>;}
