"use client";
import { Eye, EyeOff } from "lucide-react";
import { useState, type FormEvent } from "react";
import { ErrorSummary } from "@/components/error-summary";
import { Alert } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { FormField } from "@/components/ui/form-field";
import { Input } from "@/components/ui/input";
import { loginSchema } from "@/lib/validation/login";

export function LoginForm() { const [show,setShow]=useState(false);const [errors,setErrors]=useState<Array<{id:string;message:string}>>([]);const [notice,setNotice]=useState(false);function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setNotice(false);const data=new FormData(event.currentTarget);const parsed=loginSchema.safeParse({email:data.get("email"),password:data.get("password")});if(!parsed.success){setErrors(parsed.error.issues.map(issue=>({id:String(issue.path[0]),message:issue.message})));return;}setErrors([]);setNotice(true);} return <form onSubmit={submit} noValidate className="space-y-5"><ErrorSummary errors={errors} />{notice&&<Alert title="Live sign-in is not connected yet">Use one of the secure demo workspaces below. Your Supabase connection will enable account sign-in later.</Alert>}<FormField id="email" label="Email address" required error={errors.find(e=>e.id==="email")?.message}><Input id="email" name="email" type="email" autoComplete="email" aria-invalid={errors.some(e=>e.id==="email")} /></FormField><FormField id="password" label="Password" required error={errors.find(e=>e.id==="password")?.message}><div className="relative"><Input id="password" name="password" type={show?"text":"password"} autoComplete="current-password" className="pr-12" aria-invalid={errors.some(e=>e.id==="password")} /><button type="button" onClick={()=>setShow(v=>!v)} className="absolute right-1 top-1 grid size-10 place-items-center rounded-lg text-[var(--muted)] hover:bg-[var(--soft)] focus-visible:outline-none focus-visible:ring-3 focus-visible:ring-[var(--focus)]" aria-label={show?"Hide password":"Show password"}>{show?<EyeOff aria-hidden="true" className="size-4" />:<Eye aria-hidden="true" className="size-4" />}</button></div></FormField><Button className="w-full" type="submit">Sign in</Button></form>; }
