import type { Metadata } from "next";
import { PageHeading } from "@/components/page-heading";
import { StatusBadge } from "@/components/status-badge";
import { ApplicationTaskLayout } from "@/features/applications/application-task-layout";
import { DocumentUploadPanel } from "@/features/applications/document-upload-panel";
import { requireApplicationAccess } from "@/lib/auth/dal";
import { deriveApplicationProgress } from "@/lib/applications/progress";
import { createClient } from "@/lib/supabase/server";

export const metadata:Metadata={title:"Application"};

export default async function ApplicationPage({params}:{params:Promise<{applicationId:string}>}){const {application}=await requireApplicationAccess((await params).applicationId);const supabase=await createClient();const [{data:documents,error:documentsError},{data:buyer,error:buyerError}]=await Promise.all([supabase.from("documents").select("id,kind,original_filename,storage_path,byte_size,page_count,upload_completed_at").eq("application_id",application.id),supabase.from("organizations").select("name").eq("id",application.buyer_organization_id).maybeSingle()]);if(documentsError||buyerError)throw new Error("Unable to load the private application workflow.");const completedKinds=(documents??[]).filter(document=>document.upload_completed_at).map(document=>document.kind);const progress=deriveApplicationProgress(application,completedKinds);const amount=application.invoice_total_minor===null?"Amount pending":new Intl.NumberFormat("en-ZA",{style:"currency",currency:application.currency}).format(application.invoice_total_minor/100);return <ApplicationTaskLayout {...progress}><div className="page-enter"><div className="flex flex-wrap items-center gap-2"><StatusBadge status="neutral">{application.status.replaceAll("_"," ")}</StatusBadge><span className="text-xs font-semibold text-[var(--muted)]">{buyer?.name??"Private buyer"} · {amount}</span></div><div className="mt-4"><PageHeading eyebrow={`Application · ${application.id.slice(0,8).toUpperCase()}`} title={application.invoice_number??"Private draft"} description="Your details are saved. Continue one evidence step at a time; progress is kept securely in your hosted workspace."/></div><div className="mt-10"><DocumentUploadPanel applicationId={application.id} status={application.status} documents={(documents??[]).map(document=>({id:document.id,kind:document.kind,originalFilename:document.original_filename,storagePath:document.storage_path,byteSize:document.byte_size,pageCount:document.page_count,uploadCompletedAt:document.upload_completed_at}))}/></div></div></ApplicationTaskLayout>}
