import type { Metadata } from "next";
import { FileUp, LockKeyhole } from "lucide-react";
import { PageHeading } from "@/components/page-heading";
import { StatusBadge } from "@/components/status-badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { ApplicationTaskLayout } from "@/features/applications/application-task-layout";
import { requireApplicationAccess } from "@/lib/auth/dal";
import { deriveApplicationProgress } from "@/lib/applications/progress";
import { createClient } from "@/lib/supabase/server";

export const metadata:Metadata={title:"Application"};

export default async function ApplicationPage({params}:{params:Promise<{applicationId:string}>}){const {application}=await requireApplicationAccess((await params).applicationId);const supabase=await createClient();const [{data:documents,error:documentsError},{data:buyer,error:buyerError}]=await Promise.all([supabase.from("documents").select("kind").eq("application_id",application.id),supabase.from("organizations").select("name").eq("id",application.buyer_organization_id).maybeSingle()]);if(documentsError||buyerError)throw new Error("Unable to load the private application workflow.");const progress=deriveApplicationProgress(application,(documents??[]).map(document=>document.kind));const amount=application.invoice_total_minor===null?"Amount pending":new Intl.NumberFormat("en-ZA",{style:"currency",currency:application.currency}).format(application.invoice_total_minor/100);return <ApplicationTaskLayout {...progress}><div className="page-enter"><div className="flex flex-wrap items-center gap-2"><StatusBadge status="neutral">{application.status.replaceAll("_"," ")}</StatusBadge><span className="text-xs font-semibold text-[var(--muted)]">{buyer?.name??"Private buyer"} · {amount}</span></div><div className="mt-4"><PageHeading eyebrow={`Application · ${application.id.slice(0,8).toUpperCase()}`} title={application.invoice_number??"Private draft"} description="Your details are saved. Continue one evidence step at a time; progress is kept securely in your hosted workspace."/></div><Card className="mt-10 overflow-hidden"><CardContent className="pt-6"><div className="flex flex-col gap-6 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-4"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-[var(--success-soft)] text-[var(--primary)]"><FileUp className="size-5" aria-hidden="true"/></span><div><h2 className="font-bold">Add the three supporting documents</h2><p className="mt-2 max-w-lg text-sm leading-6 text-[var(--muted)]">Purchase order, delivery evidence, and invoice each receive a private named slot in the next build unit.</p></div></div><Button disabled title="Available after the secure upload unit is completed">Upload documents</Button></div><p className="mt-6 flex gap-2 border-t border-[var(--border)] pt-5 text-xs leading-5 text-[var(--muted)]"><LockKeyhole className="mt-0.5 size-4 shrink-0" aria-hidden="true"/>Review stays locked until all three documents are stored privately.</p></CardContent></Card></div></ApplicationTaskLayout>}
